export const COMPANY_TAGS = [
  'agriculture / farming',
  'climate-tech / innovation',
  'consultancy / agency',
  'design / video agencies',
  'e-commerce',
  'education',
  'energy',
  'fashion / lifestyle',
  'food / beverage',
  'gaming / entertainment',
  'hardware / appliances / electronics',
  'healthcare',
  'impact by design',
  'insurance',
  'marketing / data analytics',
  'marketplaces / platform',
  'media publishing / streaming',
  'mobility / micromobility / automotive',
  'network / events',
  'other',
  'payments / financial services',
  'physical supply chain',
  'real estate / construction',
  'software / apps',
  'tools for hr / project management',
  'transportation / logistics',
  'travel / tourism / hospitality',
  'vc',
]
