export const COMPANY_TAGS = [
  'bhag',
  'b2c',
  'b2b',
  'agriculture / farming',
  'fashion',
  'e-commerce',
  'network / events',
  'electronics',
  'design',
  'education',
  'energy',
  'payments / financial services',
  'food / beverage',
  'gaming',
  'government / society services',
  'health care',
  'investments / lending',
  'media / entertainment / content',
  'natural resources',
  'consultancies',
  'real estate',
  'sales / marketing / advertising',
  'science / engineering',
  'sports',
  'climate tech',
  'transportation / mobility',
  'travel / tourism',
  'mobile / telecommunications',
  'software / apps / platforms',
  'data / analytics',
  'information technology',
  'internet services',
  'other',
]
