name: ci
on:
  push:
    branches:
      - '**'
  repository_dispatch:
    types: [deployment-trigger]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Run linter
        run: yarn lint
        env:
          CF_ACCESS_TOKEN: ${{ secrets.CF_ACCESS_TOKEN }}
          CF_SPACE_ID: ${{ secrets.CF_SPACE_ID }}

  deploy:
    runs-on: ubuntu-latest
    needs: lint
    outputs:
      preview_url: ${{ steps.vercel-deploy.outputs.preview-url }}
    steps:
      - uses: actions/checkout@v2
      - name: Determine vercel args
        uses: haya14busa/action-cond@v1
        id: vercel-args
        with:
          cond: ${{ github.ref_name == 'main' }}
          if_true: '--prod'
          if_false: ''
      - name: Determine alias-domain
        uses: haya14busa/action-cond@v1
        id: alias-domain
        with:
          cond: ${{ github.ref_name == 'main' }}
          if_true: ''
          if_false: 'preview-lfca-open-knowledge-hub.vercel.app'
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        id: vercel-deploy
        with:
          alias-domains: ${{ steps.alias-domain.outputs.value }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          scope: ${{ secrets.VERCEL_ORG_ID }}
          vercel-args: ${{ steps.vercel-args.outputs.value }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
